<?php

namespace Isf\PublicoBundle\Repository;

/**
 * PepeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PepeRepository extends \Doctrine\ORM\EntityRepository
{
}
